name: Shotokonoko
main: io.github.highright1234.shotokonoko.ShotokonokoPlugin
version: ${version}
libraries:
  - io.github.monun:kommand-core:${kommandVersion}
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:${coroutinesVersion}